musicplayer.security.smb.username=*****
musicplayer.security.smb.password=*****

musicplayer.localresources.images.artist.thumbs=/home/luna/SHARE/musicplayer/thumbs
musicplayer.localresources.images.artist.fanarts=/home/luna/SHARE/musicplayer/fanarts
musicplayer.music-source=smb://192.168.1.51/Volume_1/musik/

musicplayer.localresources.images.supported-extensions=jpg,jpeg,png
musicplayer.localresources.images.thumbs.supported-names=thumb,miniature,folder,albumart,cover
musicplayer.localresources.images.fanart.supported-names=fanart,wallpaper

musicplayer.music.supported-extensions=mp3,wav,flac

spring.datasource.url=jdbc:h2:file:/home/luna/SHARE/musicplayer/database
spring.h2.console.settings.web-allow-others=true
server.port=80