export const SEARCH_EVENT = 'SEARCH_EVENT';
export const FORCE_CLEAR_SEARCH_EVENT = 'FORCE_CLEAR_SEARCH_EVENT';

export const DISPLAYABLE_MODULES_CHANGED = 'DISPLAYABLE_MODULES_CHANGED';

export const OTHER_MAIN_MENU_ITEM_CLICK = 'OTHER_MAIN_MENU_ITEM_CLICK';

export const FILE_BROWSER_SELECT_FILE = 'FILE_BROWSER_SELECT_FILE';
export const FILE_BROWSER_CHANGE_CURRENT_DIRECTORY = 'FILE_BROWSER_CHANGE_CURRENT_DIRECTORY';
export const FILE_BROWSER_REQUEST_DIRECTORY_DETAIL = 'FILE_BROWSER_REQUEST_DIRECTORY_DETAIL';
export const FILE_BROWSER_DIRECTORY_DETAIL_LOADED = 'FILE_BROWSER_DIRECTORY_DETAIL_LOADED';
export const FILE_BROWSER_CREATE_NEW_DIRECTORY = 'FILE_BROWSER_CREATE_NEW_DIRECTORY';
export const FILE_BROWSER_DELETE_FILES = 'FILE_BROWSER_DELETE_FILES';
export const FILE_BROWSER_RENAME_ONE_FILE = 'FILE_BROWSER_RENAME_ONE_FILE';